{
	"version": 1705566511,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/gotest-sheet0.png",
		"images/tiledbackground5.png",
		"images/sprite2-sheet0.png",
		"images/gozineh1-sheet0.png",
		"images/gizineh2-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/add-sheet0.png",
		"images/home-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/tiledbackground6.png",
		"images/tiledbackground9.png",
		"images/tiledbackground10.png",
		"images/wallpapergramir_ws1588195205_-sheet0.png",
		"images/tiledbackground11.png",
		"images/tiledbackground12.png",
		"images/tiledbackground13.png",
		"afarin (3) (online-audio-converter.com).ogg",
		"khoshhali.ogg",
		"wah-wah-sad-trombone.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"b arshia.ttf"
	]
}